#!/usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = 'You Mengyu'

"""
Visualize the data generated by ray_dynamics.py.
Change the style of plot as you like.
"""

import matplotlib.pyplot as plt
import numpy as np


def plot_traj(data_bdry, data_traj):
    plt.plot(data_bdry[:, 0], data_bdry[:, 1], c='black', linewidth=1.5)
    plt.plot(data_traj[:, 0], data_traj[:, 1], linewidth=0.3, c='black')

    plt.axis('equal')

    plt.show()


def plot_brik(data_brik):
    plt.plot(data_brik[:, 0], data_brik[:, 1], '.', c='black', markersize=0.5)

    plt.xlim([-np.pi - 0.001, np.pi + 0.001])
    plt.ylim([0, 1])

    plt.xlabel(r'phi')
    plt.ylabel(r'$\sin{\theta}$')

    plt.show()


def main():
    dirpath = './Circle_pars10_nsteps100'
    data_bdry = np.load(f'{dirpath}/boundary_data.npy')
    data_traj = np.load(f'{dirpath}/position_data.npy')
    data_brik = np.load(f'{dirpath}/brikhoff_data.npy')

    plot_traj(data_bdry, data_traj)
    plot_brik(data_brik)


if __name__ == '__main__':
    main()